### ISSUE TITLE
Helpful Media Handling (aka Feature Dreaming)

### ISSUE THREAD

**Issue by jkeefe** [propublica/timeline-setter#19]
Two possible improvements, based on experience in our newsroom: 

1) Reporters and producers are really good at finding links images and YouTube videos, but not so great at writing error-free html. So if there were a "media" column that would look for images and videos (from YouTube, at least) and make the html for that card, that'd be a great help. (For now, I'm solving this by building the html with a spreadsheet formula I add after they get me the spreadsheet. May attempt to write something into the code that does that.)

2) Related: It would be great if there were a way to set the max media width (and maybe height) for any media when timeline-setter runs ... and then have TS automatically set the img width= and height= to proportional numbers within that limit (not _actually_ resizing the file, but just displaying it at the smaller size.) As you can probably tell, that the other thing I spend a lot of time on.

Amazing tool. Thanks, guys!
John

**Comment by palewire** [comment]
I have experienced similar problems. Asking the average researcher or reporter to write valid HTML in twenty consecutive spreadsheet cells is to expect the impossible.

**Comment by thejefflarson** [comment]
Hmm. I wonder how this'd work? Max width can be set in the css, though element styles will override anything we put in there, so a straight YouTube embed would be problematic. 

Is the idea to include extra columns specifically for youtube / images that will build out custom html?

**Comment by jkeefe** [comment]
To be honest, YouTube videos are less problematic than the images -- because I just tell reporters/producers to use the embed html, and it cuts/pastes fine. 

The real issue is images. 

Spreadsheet maker finds, say, this:
http://upload.wikimedia.org/wikipedia/commons/0/0e/Andrew_Cuomo_by_Pat_Arnow_cropped.jpeg
(which is 811 x 1001 px)

That's easy enough, but then I'm asking them to put this in the spreadsheet:
img src="http://upload.wikimedia.org/wikipedia/commons/0/0e/Andrew_Cuomo_by_Pat_Arnow_cropped.jpeg" width="400" height="494" (but surrounded by carrots!)

... which is a little too susceptible to errors.

**Comment by thejefflarson** [comment]
Sorry, we've had a big week. But to play this out a little bit more, browser resizing of huge images is not good anyway you slice it, and TimelineSetter can handle bigger images than the default pretty well (without width and height attributes and as long as they're not wider than the timeline itself). Is it a big thing to host smaller versions of the huge images on your server? Otherwise with #2 we'd have to figure out the aspect ratio of the image in the ruby which would entail opening up images and figuring out the right size, and then we might as well build an image processing tool too, the slope is steep there.

As far as #1, I'm a little unclear on what to do. Like what happens if you want 2 images, or a google map, or a document cloud embed? I think it might be better for TimelineSetter to be agnostic with regards to the html, but if you've got a good solution or ideas on how to make it generic and flexible, I'm all ears and would absolutely love to brainstorm ideas. We're not sold on the csv format, but everyone seems to speak it out there.

**Comment by palewire** [comment]
Fwiw, i have a demo of a django admin that will handle the creation of a timeline and the custom html. If i ever get it out of skunkworks maube we could opensource.

**Comment by jkeefe** [comment]
Jeff ... I think you're right about TimelineSetter being agnostic. Makes a lot of sense. What I might look into is some kind of -app/plugin/dongle thing that would do some of this basic work downstream of the reporters and upstream of TimelineSetter. That way I can also tailor it to how _we_ tend to use it (which, among other things, includes iframing it at a width of 600px). Also, the max-width ability for the CSS is a great tip. Thanks.

Ben .. I'd definitely be interested in that!

**Comment by thejefflarson** [comment]
Great! I'm going to go ahead and close this in favor of a tool that'll build out these spreadsheets. We can call it TimelineSetterSetter.
