### ISSUE TITLE
Support for multiple timelines?

### ISSUE THREAD

**Issue by jgamage** [propublica/timeline-setter#23]
Hello,

Is there any support (or planned support) for drawing multiple timelines within the same page?  

I tried some quick hacking, and I think that you could pass in some kind of "base div id" in the "config" hash - then perhaps you could index and draw everything inside of that "base div id" for a particular timeline.

I'm not sure how "locked in" everything is to point to the fixed id's, but it didn't look like there were very many places that pointed to them.

Thanks!

**Comment by thejefflarson** [comment]
Sorry for the late reply, but we don't have anyplans to do so at the moment, if you'd like to take a stab at it here are some pointers:
- The TimelineSetter.boot function here:
  https://github.com/propublica/timeline-setter/blob/master/public/javascripts/timeline-setter.js#L872
  would have to be reworked as a factory, so that all the user would need to do is pass in an element that would be proxied to 
    https://github.com/propublica/timeline-setter/blob/master/public/javascripts/timeline-setter.js#L443
  and the zoom and next previous controls. 
- Then you'd have to scope everything for each timeline to the current element, I bet you could create a scoped jquery like in:
  https://github.com/propublica/timeline-setter/blob/master/public/javascripts/timeline-setter.js#L669
  for each instance of the timeline setter and use that instead of the global one. 

It might be a pretty big rewrite, but I think it's possible. The key is to scope every selector I think.

--Jeff

**Comment by ashaw** [comment]
This will be fixed in the upcoming 0.3.0 release. Stay tuned.

**Comment by jgamage** [comment]
Wonderful - thank!
