### ISSUE TITLE
-a flag not preventing overwriting of JS

### ISSUE THREAD

**Issue by tommeagher** [propublica/timeline-setter#36]
I tweak the timeline-setter.js file slightly to make "Read More" say "Read More at NJ.com" instead.

Then I run this command:
timeline-setter -ac myfile.csv

I look at the timeline-setter.js file and it's been changed back to "Read More." Appears to still be overwriting my JS and CSS folders with the defaults. Am I not using the -a flag correctly? The same thing happens when I use --without-assets.

Help!

**Comment by ashaw** [comment]
This is happening because it's using the JavaScript templates from within the TimelineSetter package ([specifically](https://github.com/propublica/timeline-setter/blob/master/public/javascripts/templates/card.jst#L13)) to generate that markup. This is tricky.. you'll have to
- grab a copy of TimelineSetter from the repo
- edit that [template](https://github.com/propublica/timeline-setter/blob/master/public/javascripts/templates/card.jst#L13)
- run `rake jammit` to add the new templates to the `JST` object 
- run `your_dir/bin/timeline-setter` to pick up the edited versions

This isn't ideal.. We should look into a better way to let users edit the templates.

**Comment by tommeagher** [comment]
Thanks, Al. 
Any reason I can't/shouldn't tweak this in the gem already installed? I see where it all is in my .rvm directory...

**Comment by ashaw** [comment]
Sure, you can do that too. Edit that template right in your gems directory, run `rake jammit` in the root of the TimelineSetter gem, and you should be good to go. Though, you might lose your changes when you update TimelineSetter. We're going to look into a way to have custom JS templates for each project.

**Comment by tommeagher** [comment]
Awesome. Thank you!

**Comment by thejefflarson** [comment]
So I just added a new argument to the onCardAdd callback so the signature is now

   function(data, card) { }

The card object has a `template` attribute which you can change to your hearts content, make sure you pass the template through _.template first.

**Comment by tommeagher** [comment]
Al, when I try to run <code>rake jammit</code>, I get this: 

(in /Users/admin/dev/timeline/timeline-setter)
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+) rake aborted!
no such file to load -- rspec/core/rake_task

I understand this about as much as I grokked Jeff's instructions on the card object, which is to say not at all.
